"""Self-contained HTML diff report for a :class:`~verdictai.seams.ChainAudit`.

The report is a single static file: inline CSS only, no CDN, no JavaScript,
no external fonts. Steps render as columns, dot-notation fields as rows, and
each cell is color-coded by what happened to that field at that seam:

- **red** — the field was produced upstream and is gone downstream (dropped)
- **amber** — the field arrived but its value or type changed (before -> after)
- **green** — the field arrived intact (kept)
- **blue** — the field is new at this step (added) or its value survives under
  another name (recovered)
- **gray** — the field does not participate in this step

Output is byte-for-byte deterministic for a given audit: fixed ordering, no
timestamps, escaped values truncated at a fixed width.
"""

from __future__ import annotations

import html
import json
from pathlib import Path
from typing import Any

from .seams import LEN_SUFFIX, ChainAudit, flatten_fields

_MAX_CELL = 80

_NEUTRAL = "cell-neutral"
_KEPT = "cell-kept"
_MUTATED = "cell-mutated"
_DROPPED = "cell-dropped"
_ADDED = "cell-added"
_RECOVERED = "cell-recovered"

_CSS = """
body{font-family:Segoe UI,Arial,Helvetica,sans-serif;margin:24px;color:#1c2430;background:#fff}
h1{font-size:20px;margin:0 0 4px 0}
h2{font-size:15px;margin:22px 0 8px 0}
.sub{color:#5a6472;font-size:13px;margin:0 0 14px 0}
.badges span{display:inline-block;border-radius:4px;padding:3px 10px;margin-right:8px;
 font-size:12px;font-weight:600;background:#eef1f5;border:1px solid #d6dce4}
table{border-collapse:collapse;font-size:12px;margin-top:8px}
th,td{border:1px solid #d6dce4;padding:4px 8px;text-align:left;vertical-align:top}
th.step{background:#1c2430;color:#fff;font-size:13px}
th.fidelity{background:#eef1f5;font-weight:600;font-size:11px;color:#33404f}
td.field{font-family:Consolas,Menlo,monospace;color:#33404f;white-space:nowrap}
td code{font-family:Consolas,Menlo,monospace;font-size:11px}
.cell-kept{background:#d4edda}
.cell-mutated{background:#fff3cd}
.cell-dropped{background:#f8d7da;color:#842029;font-weight:600}
.cell-added{background:#cfe2ff}
.cell-recovered{background:#d1ecf1}
.cell-neutral{background:#f8f9fa;color:#5a6472}
.legend{font-size:12px;margin-top:10px}
.legend span.sw{display:inline-block;width:12px;height:12px;margin:0 4px 0 12px;
 vertical-align:-1px;border:1px solid #b8c0ca}
table.blame td,table.blame th{font-size:12px}
.mono{font-family:Consolas,Menlo,monospace}
footer{margin-top:26px;color:#8a93a0;font-size:11px}
"""


def _fmt(value: Any) -> str:
    """Deterministic, escaped, truncated cell text for a leaf value."""
    if value is None:
        text = "null"
    elif isinstance(value, str):
        text = value
    else:
        text = json.dumps(value, sort_keys=True, ensure_ascii=False)
    text = html.escape(text)
    if len(text) > _MAX_CELL:
        text = text[: _MAX_CELL - 1] + "…"
    return text


class HtmlDiffReport:
    """Render a chain audit as a standalone HTML file."""

    @classmethod
    def generate(cls, chain_audit: ChainAudit, out_path: str | Path) -> str:
        """Write the report and return the HTML string written."""
        doc = cls._render(chain_audit)
        Path(out_path).write_text(doc, encoding="utf-8")
        return doc

    # Rendering pieces -----------------------------------------------------

    @classmethod
    def _render(cls, audit: ChainAudit) -> str:
        parts: list[str] = [
            "<!DOCTYPE html>",
            '<html lang="en"><head><meta charset="utf-8">',
            "<title>VerdictAI Seam Audit</title>",
            f"<style>{_CSS}</style></head><body>",
            "<h1>Seam audit report</h1>",
            '<p class="sub">Deterministic handoff-fidelity analysis across '
            "agent steps — no LLM calls involved.</p>",
            cls._badges(audit),
            cls._matrix(audit),
            cls._legend(),
            cls._blame(audit),
            "<footer>Generated by VerdictAI HtmlDiffReport — static, "
            "self-contained, deterministic.</footer>",
            "</body></html>",
        ]
        return "".join(parts)

    @classmethod
    def _badges(cls, audit: ChainAudit) -> str:
        halflife = (
            f"{audit.fidelity_halflife} handoff(s)"
            if audit.fidelity_halflife is not None
            else "never"
        )
        return (
            '<p class="badges">'
            f"<span>steps: {len(audit.steps)}</span>"
            f"<span>seams: {len(audit.handoffs)}</span>"
            f"<span>chain fidelity: {audit.chain_fidelity:.3f}</span>"
            f"<span>fidelity halflife: {halflife} (&lt;0.5)</span>"
            "</p>"
        )

    @classmethod
    def _matrix(cls, audit: ChainAudit) -> str:
        """The steps-as-columns / fields-as-rows grid."""
        if not audit.steps:
            return "<p>No steps in trace.</p>"
        per_step_in: list[dict[str, Any]] = []
        per_step_out: list[dict[str, Any]] = []
        rows: list[str] = []
        fields: list[str] = []
        seen: set[str] = set()

        def payload_leaves(payload: dict[str, Any]) -> dict[str, Any]:
            leaves, lengths = flatten_fields(payload)
            for path, length in lengths.items():
                leaves[f"{path}{LEN_SUFFIX}"] = length
            return leaves

        for step in audit.steps:
            leaves_in = payload_leaves(step.input)
            leaves_out = payload_leaves(step.output)
            per_step_in.append(leaves_in)
            per_step_out.append(leaves_out)
            for field in [*leaves_out, *leaves_in]:
                if field not in seen:
                    seen.add(field)
                    fields.append(field)

        header = [
            "<table>",
            "<tr><th class=\"step\">field (dot-notation)</th>",
        ]
        header += [f'<th class="step">{html.escape(s.name)}</th>' for s in audit.steps]
        header.append("</tr>")
        rows.append("".join(header))

        fidelity_row = ['<tr><th class="fidelity">handoff fidelity</th>']
        for i, _step in enumerate(audit.steps):
            if i == 0:
                fidelity_row.append('<th class="fidelity">—</th>')
            else:
                diff = audit.handoffs[i - 1]
                note = (
                    f" · {len(diff.dropped_fields)} dropped"
                    f" · {len(diff.mutated)} mutated"
                    if diff.dropped_fields or diff.mutated
                    else ""
                )
                fidelity_row.append(
                    f'<th class="fidelity">{diff.fidelity:.3f}'
                    f"{html.escape(note)}</th>"
                )
        fidelity_row.append("</tr>")
        rows.append("".join(fidelity_row))

        for field in fields:
            cells = [f'<td class="field"><code>{html.escape(field)}</code></td>']
            for i in range(len(audit.steps)):
                cells.append(cls._cell(audit, i, field, per_step_in, per_step_out))
            rows.append("<tr>" + "".join(cells) + "</tr>")
        rows.append("</table>")
        return "".join(rows)

    @classmethod
    def _cell(
        cls,
        audit: ChainAudit,
        i: int,
        field: str,
        per_step_in: list[dict[str, Any]],
        per_step_out: list[dict[str, Any]],
    ) -> str:
        if i == 0:
            if field in per_step_in[0]:
                return (
                    f'<td class="{_NEUTRAL}">{_fmt(per_step_in[0][field])} '
                    "<code>(in)</code></td>"
                )
            if field in per_step_out[0]:
                return f'<td class="{_NEUTRAL}">{_fmt(per_step_out[0][field])}</td>'
            return '<td class="' + _NEUTRAL + '"></td>'

        diff = audit.handoffs[i - 1]
        prev_out = per_step_out[i - 1]
        cur_in = per_step_in[i]
        cur_out = per_step_out[i]

        mutation = next((m for m in diff.mutated if m.field == field), None)
        type_change = next((t for t in diff.type_changed if t.field == field), None)
        if mutation is not None:
            return (
                f'<td class="{_MUTATED}">{_fmt(mutation.before)} → {_fmt(mutation.after)}</td>'
            )
        if type_change is not None:
            return (
                f'<td class="{_MUTATED}">{html.escape(type_change.before_type)} → '
                f"{html.escape(type_change.after_type)} (type)</td>"
            )
        if field in cur_in:
            if field in prev_out:
                return f'<td class="{_KEPT}">{_fmt(cur_in[field])}</td>'
            return f'<td class="{_ADDED}">{_fmt(cur_in[field])} <code>(new)</code></td>'
        if field in diff.dropped_fields:
            return '<td class="' + _DROPPED + '">dropped</td>'
        if field in prev_out and prev_out[field] in set(cur_in.values()):
            return (
                f'<td class="{_RECOVERED}">{_fmt(prev_out[field])} '
                "<code>(recovered elsewhere)</code></td>"
            )
        if field in cur_out:
            return f'<td class="{_NEUTRAL}">{_fmt(cur_out[field])} <code>(out)</code></td>'
        return '<td class="' + _NEUTRAL + '"></td>'

    @classmethod
    def _legend(cls) -> str:
        items = [
            (_KEPT, "kept — field arrived intact"),
            (_MUTATED, "mutated — value/type changed (before → after)"),
            (_DROPPED, "dropped — produced upstream, absent downstream"),
            (_ADDED, "added — new field at this step"),
            (_RECOVERED, "recovered — value survives under another field"),
            (_NEUTRAL, "not part of this seam"),
        ]
        swatches = "".join(
            f'<span class="sw {css}"></span>{html.escape(label)}' for css, label in items
        )
        return f'<p class="legend">{swatches}</p>'

    @classmethod
    def _blame(cls, audit: ChainAudit) -> str:
        entries = audit.blame()
        if not entries:
            return ""
        rows = [
            "<h2>Blame attribution (worst seam first)</h2>",
            '<table class="blame">',
            "<tr><th>rank</th><th>seam</th><th>fidelity</th>"
            "<th>downstream steps</th><th>severity</th></tr>",
        ]
        for rank, entry in enumerate(entries, start=1):
            rows.append(
                "<tr>"
                f"<td>{rank}</td>"
                f'<td class="mono">{html.escape(entry.from_step)} → '
                f"{html.escape(entry.to_step)}</td>"
                f"<td>{entry.fidelity:.3f}</td>"
                f"<td>{entry.downstream_steps}</td>"
                f'<td class="mono">{entry.severity:.3f}</td>'
                "</tr>"
            )
        rows.append("</table>")
        return "".join(rows)
